const body = {
  Id: 0,
  EventId: process.env.EVENT_ID,
  Email: "contact_email",
  IncludeTicketGuarantee: false,
  IsTicketClaimRequired: false,
  Language: "string",
  TotalAmount: "line_items.fulfillable_quantity",
  Reference: "string",
  // BasketId: 0,
  SuccessfulPurchaseRedirectUrl: "string",
  FailedPurchaseRedirectUrl: "string",
  PurchaseFailedWebhookUrl: "string",
  PurchaseSuccessWebhookUrl: "string",
  HasAcceptedTermsAndAgreements: true,
  // PaymentUrl: "string",
  Secret: "string",
  Paid: true,
  Complimentary: true,
  PaidDate: "2023-10-27T15:06:33.518Z",
  // Cancelled: true,
  // DiscountCode: "string",
  PurchaseItems: [
    {
      Id: 0,
      PurchaseId: 0,
      TicketId: 0,
      TimeslotIdsForTicket: ["string"],
      HasToBeClaimed: true,
      IsClaimed: true,
      ClaimDateTime: "2023-10-27T15:06:33.518Z",
      Barcode: 0,
      TicketHolderEmail: "string",
      TicketHolderFirstname: "string",
      TicketHolderInsertion: "string",
      TicketHolderLastname: "string",
      TicketHolderOrganisation: "string",
      TicketHolderDepartment: "string",
      TicketHolderPosition: "string",
      TicketHolderAddress: "string",
      TicketHolderCity: "string",
      TicketHolderPostalCode: "string",
      TicketHolderCountry: "string",
      TicketHolderID: "string",
      TicketHolderDateOfBirth: "2023-10-27T15:06:33.518Z",
      TicketHolderMobile: "string",
      TicketHolderPhone: "string",
      TicketHolderGender: "string",
      TicketHolderNewsletterSubscribe: true,
      IsGroupTicket: true,
      NumberOfUsersAllowedEntranceWithTicket: 0,
      CustomQuestionAnswers: [
        {
          QuestionId: 0,
          SingleAnswer: "string",
          CheckboxAnswer: true,
          MultipleAnswers: ["string"],
        },
      ],
    },
  ],
};

module.exports = body;
